---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: articles
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - blog-posts
- type: heading
  label: Pages
- type: document
  path: data/home.yaml
  label: Home
- type: document
  path: data/archive.yaml
  label: Archive
- type: document
  path: data/contact.yaml
  label: Contact
upload_dir: ''
public_path: https://res.cloudinary.com/mmattner/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn build
