---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/writing
  label: Articles
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - articles
- type: directory
  path: content/tag
  label: Tags
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - tags
- type: heading
  label: Pages
- type: document
  path: data/data.yaml
  label: About
  match: "**/*"
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn run dev
