---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: nuxt-portfolio/articles
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - blog-posts
- type: heading
  label: Pages
- type: document
  path: nuxt-portfolio/data/home.yaml
  label: Home
- type: document
  path: nuxt-portfolio/data/contact.yaml
  label: Contact
  match: "**/*"
upload_dir: ''
public_path: https://res.cloudinary.com/mmattner/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
